const APP_ROLES=Object.freeze({SYSTEM_ADMIN:'SYSTEM_ADMIN',SCHOOL_ADMIN:'SCHOOL_ADMIN',TEACHER:'TEACHER',STUDENT:'STUDENT',PARENT:'PARENT',GUEST:'GUEST'});
const APP_STATUSES=Object.freeze({ACTIVE:'ACTIVE',INACTIVE:'INACTIVE',DELETED:'DELETED'});
const EXAM_STATUSES=Object.freeze({IN_PROGRESS:'IN_PROGRESS',SUBMITTED:'SUBMITTED',AUTO_SUBMITTED:'AUTO_SUBMITTED',GRADED:'GRADED'});
const QUESTION_TYPES=Object.freeze({MCQ:'MCQ',TRUE_FALSE:'TRUE_FALSE',MULTIPLE_ANSWER:'MULTIPLE_ANSWER',SHORT_TEXT:'SHORT_TEXT',ESSAY:'ESSAY',NUMERIC:'NUMERIC'});
